server:
  port: 8000
spring:
  sql:
    init:
      mode: always

  application:
    name: crud
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/crud?crateIfNotExist=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  security:
    user:
      name: sofi
      password: 1234sofi
      roles: admin
